theme: jekyll-theme-cayman

title: ozeno

author:
  fullname                  : Your Name
  rss                       : true # generate RSS feed and show it's icon in header
  mail                      : your@email.com # change to your e-mail address
  twitter                   : twitter-user-name
  github                    : github-user-name
  youtube                   : youtube-user-name
  stackoverflow             : stackoverflow-user-name
  disqus                    : dactl # your disqus site name
  google_analytics          : # 'UA-XXXXXXXX-X'
  photo                     : "uploads/me2.png"
  photo2x                   : "uploads/me.png"